apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb-dev
  namespace: argocd
spec:
  project: tools
  sources:
    - repoURL: https://mongodb.github.io/helm-charts
      targetRevision: 0.9.0
      chart: community-operator
      helm:
        releaseName: mongodb-dev
      
    - repoURL: https://github.com/open-liontechsolution/fintech-personal-tools.git
      targetRevision: HEAD
      path: apps/mongodb/helm-values/dev
      
  destination:
    server: https://kubernetes.default.svc
    namespace: mongodb-dev
  syncPolicy:
    automated:
      # Desactivamos el prune autom√°tico para evitar que ArgoCD elimine recursos que no controla
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
